#!/bin/bash

# runmacpy
# Nathan Tarr
# Give this file executable privileges (chmod +x runpy)

# Change this to the directory path this file is contained in
cd `dirname $0`

function pause() {
	read -p "$*"
}

pythonw startconfig.py

if [ $? -eq 0 ] 
	then 
		pythonw2.4 project.py
fi

pause 'Press key on keyboard to continue...'
